"""
PLAN step of the agentic workflow.

Given a free-text music request, produces a Plan: structured preferences
(genre/mood/energy) extracted from the request, a scoring strategy, and an
ordered list of steps for the Actor to execute. The plan is generated by
an LLM call when available, and by deterministic keyword matching when it
is not (missing API key, network failure, or a malformed LLM response).

Keeping this separate from actor.py is the whole point of the plan/act
split: the Planner only ever *decides what to do*. It never touches the
song catalog or does any scoring itself.
"""

import json
from dataclasses import dataclass, field
from typing import Dict, List, Optional

from .llm_client import call_llm_json
from .logger import get_logger

logger = get_logger()

DEFAULT_K = 5
DEFAULT_ENERGY = 0.6

SYSTEM_PROMPT = """You are the planning module of a music recommendation agent.
Given a free-text user request and the genres/moods that actually exist in the
song catalog, extract structured preferences and produce a short ordered plan.

Respond with ONLY a JSON object (no prose, no markdown fences) matching this
exact shape:
{
  "preferences": {"genre": <string>, "mood": <string>, "energy": <float 0-1>},
  "strategy": {"require_genre_match": <bool>, "k": <int>},
  "steps": [
    {"id": 1, "action": "validate_input", "description": <string>},
    {"id": 2, "action": "load_catalog", "description": <string>},
    {"id": 3, "action": "score_and_rank", "description": <string>},
    {"id": 4, "action": "format_output", "description": <string>}
  ]
}

Rules:
- "genre" and "mood" should be your best guess at values from the catalog's
  known genre/mood lists, even if the user's wording doesn't match exactly.
- "energy" is a float between 0 (calm/low energy) and 1 (intense/high energy).
- The four steps (validate_input, load_catalog, score_and_rank, format_output)
  must always appear in that order -- only their descriptions should change.
- If feedback from a previous failed attempt is provided, adjust "strategy"
  to address it (e.g. set require_genre_match to false if the previous
  attempt's matches were too weak).
"""


@dataclass
class Plan:
    preferences: Dict
    strategy: Dict
    steps: List[Dict]
    source: str  # "llm" or "deterministic_fallback"


def _deterministic_plan(user_request: str, known_genres: List[str], known_moods: List[str],
                         feedback: Optional[Dict]) -> Plan:
    """
    Rule-based fallback: substring-match known genres/moods against the
    request text. This exists so the agent still produces a usable plan
    (and the demo/tests still run) with no API key and no network access.
    """
    text = user_request.lower()

    genre = next((g for g in known_genres if g.lower() in text), known_genres[0])
    mood = next((m for m in known_moods if m.lower() in text), known_moods[0])

    if any(word in text for word in ("high energy", "intense", "workout", "upbeat", "energetic")):
        energy = 0.9
    elif any(word in text for word in ("chill", "calm", "relax", "low energy", "mellow", "slow")):
        energy = 0.3
    else:
        energy = DEFAULT_ENERGY

    require_genre_match = True
    if feedback and feedback.get("reason") == "low_score":
        require_genre_match = False
        logger.info("Deterministic planner relaxing genre requirement per retry feedback")

    preferences = {"genre": genre, "mood": mood, "energy": energy}
    strategy = {"require_genre_match": require_genre_match, "k": DEFAULT_K}
    steps = [
        {"id": 1, "action": "validate_input", "description": "Check preferences are well-formed"},
        {"id": 2, "action": "load_catalog", "description": "Load the song catalog from CSV"},
        {"id": 3, "action": "score_and_rank", "description": "Score songs against preferences and rank them"},
        {"id": 4, "action": "format_output", "description": "Format top results with explanations"},
    ]

    return Plan(preferences=preferences, strategy=strategy, steps=steps, source="deterministic_fallback")


def _validate_llm_plan(data: Dict) -> bool:
    """Guards against a structurally-valid-JSON-but-wrong-shape LLM response."""
    try:
        prefs = data["preferences"]
        strategy = data["strategy"]
        steps = data["steps"]
        assert isinstance(prefs.get("genre"), str)
        assert isinstance(prefs.get("mood"), str)
        assert isinstance(prefs.get("energy"), (int, float))
        assert isinstance(strategy.get("require_genre_match"), bool)
        assert isinstance(strategy.get("k"), int)
        assert isinstance(steps, list) and len(steps) > 0
        return True
    except (KeyError, AssertionError, TypeError, AttributeError):
        return False


def build_plan(user_request: str, known_genres: List[str], known_moods: List[str],
                feedback: Optional[Dict] = None) -> Plan:
    """
    Produces a Plan for the given request, trying the LLM first and falling
    back to deterministic extraction. Always logs the resulting plan so the
    full decision trail is visible regardless of which path produced it.
    """
    if not user_request or not user_request.strip():
        raise ValueError("user_request must be a non-empty string")

    user_prompt = f"User request: {user_request!r}\n"
    user_prompt += f"Known genres: {known_genres}\n"
    user_prompt += f"Known moods: {known_moods}\n"
    if feedback:
        user_prompt += f"Previous attempt failed. Feedback to address: {json.dumps(feedback)}\n"

    plan = None
    llm_result = call_llm_json(SYSTEM_PROMPT, user_prompt)

    if llm_result is not None and _validate_llm_plan(llm_result):
        plan = Plan(
            preferences=llm_result["preferences"],
            strategy=llm_result["strategy"],
            steps=llm_result["steps"],
            source="llm",
        )
    elif llm_result is not None:
        logger.warning("LLM plan response had unexpected shape; falling back to deterministic planner")

    if plan is None:
        plan = _deterministic_plan(user_request, known_genres, known_moods, feedback)

    logger.info(
        "[PLAN] (%s) preferences=%s strategy=%s steps=%s",
        plan.source, plan.preferences, plan.strategy, [s["action"] for s in plan.steps],
    )

    return plan
